name: Deploy to EC2

# Triggers on every push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 — SSH into EC2 and deploy
  - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}   # ← use password instead of key
          script: |
            cd ~/docker_prac1
            git pull origin main
            docker compose up --build -d
            docker image prune -f
